mybatis:
  mapper-locations:
    - classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cheval?serverTimezone=UTC&characterEncoding=UTF-8 # TODO MySQL Docker ??? ?? ? Docker Compose ??
    username: cheval
    password: qwer1234!@
    driver-class-name: com.mysql.cj.jdbc.Driver