mybatis:
  mapper-locations:
    - classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cheval?serverTimezone=UTC&characterEncoding=UTF-8 # TODO MySQL User Account 추가 필요
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver